// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package com.google.protobuf.descriptor



@SerialVersionUID(0L)
final case class FileOptions(
    javaPackage: scala.Option[String] = None,
    javaOuterClassname: scala.Option[String] = None,
    javaMultipleFiles: scala.Option[Boolean] = None,
    javaGenerateEqualsAndHash: scala.Option[Boolean] = None,
    javaStringCheckUtf8: scala.Option[Boolean] = None,
    optimizeFor: scala.Option[com.google.protobuf.descriptor.FileOptions.OptimizeMode] = None,
    goPackage: scala.Option[String] = None,
    ccGenericServices: scala.Option[Boolean] = None,
    javaGenericServices: scala.Option[Boolean] = None,
    pyGenericServices: scala.Option[Boolean] = None,
    deprecated: scala.Option[Boolean] = None,
    ccEnableArenas: scala.Option[Boolean] = None,
    objcClassPrefix: scala.Option[String] = None,
    csharpNamespace: scala.Option[String] = None,
    uninterpretedOption: scala.collection.Seq[com.google.protobuf.descriptor.UninterpretedOption] = Nil
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[FileOptions] with com.trueaccord.lenses.Updatable[FileOptions] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      if (javaPackage.isDefined) { __size += com.google.protobuf.CodedOutputStream.computeStringSize(1, javaPackage.get) }
      if (javaOuterClassname.isDefined) { __size += com.google.protobuf.CodedOutputStream.computeStringSize(8, javaOuterClassname.get) }
      if (javaMultipleFiles.isDefined) { __size += com.google.protobuf.CodedOutputStream.computeBoolSize(10, javaMultipleFiles.get) }
      if (javaGenerateEqualsAndHash.isDefined) { __size += com.google.protobuf.CodedOutputStream.computeBoolSize(20, javaGenerateEqualsAndHash.get) }
      if (javaStringCheckUtf8.isDefined) { __size += com.google.protobuf.CodedOutputStream.computeBoolSize(27, javaStringCheckUtf8.get) }
      if (optimizeFor.isDefined) { __size += com.google.protobuf.CodedOutputStream.computeEnumSize(9, optimizeFor.get.value) }
      if (goPackage.isDefined) { __size += com.google.protobuf.CodedOutputStream.computeStringSize(11, goPackage.get) }
      if (ccGenericServices.isDefined) { __size += com.google.protobuf.CodedOutputStream.computeBoolSize(16, ccGenericServices.get) }
      if (javaGenericServices.isDefined) { __size += com.google.protobuf.CodedOutputStream.computeBoolSize(17, javaGenericServices.get) }
      if (pyGenericServices.isDefined) { __size += com.google.protobuf.CodedOutputStream.computeBoolSize(18, pyGenericServices.get) }
      if (deprecated.isDefined) { __size += com.google.protobuf.CodedOutputStream.computeBoolSize(23, deprecated.get) }
      if (ccEnableArenas.isDefined) { __size += com.google.protobuf.CodedOutputStream.computeBoolSize(31, ccEnableArenas.get) }
      if (objcClassPrefix.isDefined) { __size += com.google.protobuf.CodedOutputStream.computeStringSize(36, objcClassPrefix.get) }
      if (csharpNamespace.isDefined) { __size += com.google.protobuf.CodedOutputStream.computeStringSize(37, csharpNamespace.get) }
      uninterpretedOption.foreach(uninterpretedOption => __size += 2 + com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(uninterpretedOption.serializedSize) + uninterpretedOption.serializedSize)
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: com.google.protobuf.CodedOutputStream): Unit = {
      javaPackage.foreach { __v => 
        _output__.writeString(1, __v)
      };
      javaOuterClassname.foreach { __v => 
        _output__.writeString(8, __v)
      };
      optimizeFor.foreach { __v => 
        _output__.writeEnum(9, __v.value)
      };
      javaMultipleFiles.foreach { __v => 
        _output__.writeBool(10, __v)
      };
      goPackage.foreach { __v => 
        _output__.writeString(11, __v)
      };
      ccGenericServices.foreach { __v => 
        _output__.writeBool(16, __v)
      };
      javaGenericServices.foreach { __v => 
        _output__.writeBool(17, __v)
      };
      pyGenericServices.foreach { __v => 
        _output__.writeBool(18, __v)
      };
      javaGenerateEqualsAndHash.foreach { __v => 
        _output__.writeBool(20, __v)
      };
      deprecated.foreach { __v => 
        _output__.writeBool(23, __v)
      };
      javaStringCheckUtf8.foreach { __v => 
        _output__.writeBool(27, __v)
      };
      ccEnableArenas.foreach { __v => 
        _output__.writeBool(31, __v)
      };
      objcClassPrefix.foreach { __v => 
        _output__.writeString(36, __v)
      };
      csharpNamespace.foreach { __v => 
        _output__.writeString(37, __v)
      };
      uninterpretedOption.foreach { __v => 
        _output__.writeTag(999, 2)
        _output__.writeUInt32NoTag(__v.serializedSize)
        __v.writeTo(_output__)
      };
    }
    def mergeFrom(`_input__`: com.google.protobuf.CodedInputStream): com.google.protobuf.descriptor.FileOptions = {
      var __javaPackage = this.javaPackage
      var __javaOuterClassname = this.javaOuterClassname
      var __javaMultipleFiles = this.javaMultipleFiles
      var __javaGenerateEqualsAndHash = this.javaGenerateEqualsAndHash
      var __javaStringCheckUtf8 = this.javaStringCheckUtf8
      var __optimizeFor = this.optimizeFor
      var __goPackage = this.goPackage
      var __ccGenericServices = this.ccGenericServices
      var __javaGenericServices = this.javaGenericServices
      var __pyGenericServices = this.pyGenericServices
      var __deprecated = this.deprecated
      var __ccEnableArenas = this.ccEnableArenas
      var __objcClassPrefix = this.objcClassPrefix
      var __csharpNamespace = this.csharpNamespace
      val __uninterpretedOption = (scala.collection.immutable.Vector.newBuilder[com.google.protobuf.descriptor.UninterpretedOption] ++= this.uninterpretedOption)
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __javaPackage = Some(_input__.readString())
          case 66 =>
            __javaOuterClassname = Some(_input__.readString())
          case 80 =>
            __javaMultipleFiles = Some(_input__.readBool())
          case 160 =>
            __javaGenerateEqualsAndHash = Some(_input__.readBool())
          case 216 =>
            __javaStringCheckUtf8 = Some(_input__.readBool())
          case 72 =>
            __optimizeFor = Some(com.google.protobuf.descriptor.FileOptions.OptimizeMode.fromValue(_input__.readEnum()))
          case 90 =>
            __goPackage = Some(_input__.readString())
          case 128 =>
            __ccGenericServices = Some(_input__.readBool())
          case 136 =>
            __javaGenericServices = Some(_input__.readBool())
          case 144 =>
            __pyGenericServices = Some(_input__.readBool())
          case 184 =>
            __deprecated = Some(_input__.readBool())
          case 248 =>
            __ccEnableArenas = Some(_input__.readBool())
          case 290 =>
            __objcClassPrefix = Some(_input__.readString())
          case 298 =>
            __csharpNamespace = Some(_input__.readString())
          case 7994 =>
            __uninterpretedOption += com.trueaccord.scalapb.LiteParser.readMessage(_input__, com.google.protobuf.descriptor.UninterpretedOption.defaultInstance)
          case tag => _input__.skipField(tag)
        }
      }
      com.google.protobuf.descriptor.FileOptions(
          javaPackage = __javaPackage,
          javaOuterClassname = __javaOuterClassname,
          javaMultipleFiles = __javaMultipleFiles,
          javaGenerateEqualsAndHash = __javaGenerateEqualsAndHash,
          javaStringCheckUtf8 = __javaStringCheckUtf8,
          optimizeFor = __optimizeFor,
          goPackage = __goPackage,
          ccGenericServices = __ccGenericServices,
          javaGenericServices = __javaGenericServices,
          pyGenericServices = __pyGenericServices,
          deprecated = __deprecated,
          ccEnableArenas = __ccEnableArenas,
          objcClassPrefix = __objcClassPrefix,
          csharpNamespace = __csharpNamespace,
          uninterpretedOption = __uninterpretedOption.result()
      )
    }
    def getJavaPackage: String = javaPackage.getOrElse("")
    def clearJavaPackage: FileOptions = copy(javaPackage = None)
    def withJavaPackage(__v: String): FileOptions = copy(javaPackage = Some(__v))
    def getJavaOuterClassname: String = javaOuterClassname.getOrElse("")
    def clearJavaOuterClassname: FileOptions = copy(javaOuterClassname = None)
    def withJavaOuterClassname(__v: String): FileOptions = copy(javaOuterClassname = Some(__v))
    def getJavaMultipleFiles: Boolean = javaMultipleFiles.getOrElse(false)
    def clearJavaMultipleFiles: FileOptions = copy(javaMultipleFiles = None)
    def withJavaMultipleFiles(__v: Boolean): FileOptions = copy(javaMultipleFiles = Some(__v))
    def getJavaGenerateEqualsAndHash: Boolean = javaGenerateEqualsAndHash.getOrElse(false)
    def clearJavaGenerateEqualsAndHash: FileOptions = copy(javaGenerateEqualsAndHash = None)
    def withJavaGenerateEqualsAndHash(__v: Boolean): FileOptions = copy(javaGenerateEqualsAndHash = Some(__v))
    def getJavaStringCheckUtf8: Boolean = javaStringCheckUtf8.getOrElse(false)
    def clearJavaStringCheckUtf8: FileOptions = copy(javaStringCheckUtf8 = None)
    def withJavaStringCheckUtf8(__v: Boolean): FileOptions = copy(javaStringCheckUtf8 = Some(__v))
    def getOptimizeFor: com.google.protobuf.descriptor.FileOptions.OptimizeMode = optimizeFor.getOrElse(com.google.protobuf.descriptor.FileOptions.OptimizeMode.SPEED)
    def clearOptimizeFor: FileOptions = copy(optimizeFor = None)
    def withOptimizeFor(__v: com.google.protobuf.descriptor.FileOptions.OptimizeMode): FileOptions = copy(optimizeFor = Some(__v))
    def getGoPackage: String = goPackage.getOrElse("")
    def clearGoPackage: FileOptions = copy(goPackage = None)
    def withGoPackage(__v: String): FileOptions = copy(goPackage = Some(__v))
    def getCcGenericServices: Boolean = ccGenericServices.getOrElse(false)
    def clearCcGenericServices: FileOptions = copy(ccGenericServices = None)
    def withCcGenericServices(__v: Boolean): FileOptions = copy(ccGenericServices = Some(__v))
    def getJavaGenericServices: Boolean = javaGenericServices.getOrElse(false)
    def clearJavaGenericServices: FileOptions = copy(javaGenericServices = None)
    def withJavaGenericServices(__v: Boolean): FileOptions = copy(javaGenericServices = Some(__v))
    def getPyGenericServices: Boolean = pyGenericServices.getOrElse(false)
    def clearPyGenericServices: FileOptions = copy(pyGenericServices = None)
    def withPyGenericServices(__v: Boolean): FileOptions = copy(pyGenericServices = Some(__v))
    def getDeprecated: Boolean = deprecated.getOrElse(false)
    def clearDeprecated: FileOptions = copy(deprecated = None)
    def withDeprecated(__v: Boolean): FileOptions = copy(deprecated = Some(__v))
    def getCcEnableArenas: Boolean = ccEnableArenas.getOrElse(false)
    def clearCcEnableArenas: FileOptions = copy(ccEnableArenas = None)
    def withCcEnableArenas(__v: Boolean): FileOptions = copy(ccEnableArenas = Some(__v))
    def getObjcClassPrefix: String = objcClassPrefix.getOrElse("")
    def clearObjcClassPrefix: FileOptions = copy(objcClassPrefix = None)
    def withObjcClassPrefix(__v: String): FileOptions = copy(objcClassPrefix = Some(__v))
    def getCsharpNamespace: String = csharpNamespace.getOrElse("")
    def clearCsharpNamespace: FileOptions = copy(csharpNamespace = None)
    def withCsharpNamespace(__v: String): FileOptions = copy(csharpNamespace = Some(__v))
    def clearUninterpretedOption = copy(uninterpretedOption = scala.collection.Seq.empty)
    def addUninterpretedOption(__vs: com.google.protobuf.descriptor.UninterpretedOption*): FileOptions = addAllUninterpretedOption(__vs)
    def addAllUninterpretedOption(__vs: TraversableOnce[com.google.protobuf.descriptor.UninterpretedOption]): FileOptions = copy(uninterpretedOption = uninterpretedOption ++ __vs)
    def withUninterpretedOption(__v: scala.collection.Seq[com.google.protobuf.descriptor.UninterpretedOption]): FileOptions = copy(uninterpretedOption = __v)
    def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
      __field.getNumber match {
        case 1 => javaPackage.getOrElse(null)
        case 8 => javaOuterClassname.getOrElse(null)
        case 10 => javaMultipleFiles.getOrElse(null)
        case 20 => javaGenerateEqualsAndHash.getOrElse(null)
        case 27 => javaStringCheckUtf8.getOrElse(null)
        case 9 => optimizeFor.map(_.valueDescriptor).getOrElse(null)
        case 11 => goPackage.getOrElse(null)
        case 16 => ccGenericServices.getOrElse(null)
        case 17 => javaGenericServices.getOrElse(null)
        case 18 => pyGenericServices.getOrElse(null)
        case 23 => deprecated.getOrElse(null)
        case 31 => ccEnableArenas.getOrElse(null)
        case 36 => objcClassPrefix.getOrElse(null)
        case 37 => csharpNamespace.getOrElse(null)
        case 999 => uninterpretedOption
      }
    }
    override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.google.protobuf.descriptor.FileOptions
}

object FileOptions extends com.trueaccord.scalapb.GeneratedMessageCompanion[com.google.protobuf.descriptor.FileOptions] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[com.google.protobuf.descriptor.FileOptions] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.google.protobuf.descriptor.FileOptions = {
    require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
    val __fields = descriptor.getFields
    com.google.protobuf.descriptor.FileOptions(
      __fieldsMap.get(__fields.get(0)).asInstanceOf[scala.Option[String]],
      __fieldsMap.get(__fields.get(1)).asInstanceOf[scala.Option[String]],
      __fieldsMap.get(__fields.get(2)).asInstanceOf[scala.Option[Boolean]],
      __fieldsMap.get(__fields.get(3)).asInstanceOf[scala.Option[Boolean]],
      __fieldsMap.get(__fields.get(4)).asInstanceOf[scala.Option[Boolean]],
      __fieldsMap.get(__fields.get(5)).asInstanceOf[scala.Option[com.google.protobuf.Descriptors.EnumValueDescriptor]].map(__e => com.google.protobuf.descriptor.FileOptions.OptimizeMode.fromValue(__e.getNumber)),
      __fieldsMap.get(__fields.get(6)).asInstanceOf[scala.Option[String]],
      __fieldsMap.get(__fields.get(7)).asInstanceOf[scala.Option[Boolean]],
      __fieldsMap.get(__fields.get(8)).asInstanceOf[scala.Option[Boolean]],
      __fieldsMap.get(__fields.get(9)).asInstanceOf[scala.Option[Boolean]],
      __fieldsMap.get(__fields.get(10)).asInstanceOf[scala.Option[Boolean]],
      __fieldsMap.get(__fields.get(11)).asInstanceOf[scala.Option[Boolean]],
      __fieldsMap.get(__fields.get(12)).asInstanceOf[scala.Option[String]],
      __fieldsMap.get(__fields.get(13)).asInstanceOf[scala.Option[String]],
      __fieldsMap.getOrElse(__fields.get(14), Nil).asInstanceOf[scala.collection.Seq[com.google.protobuf.descriptor.UninterpretedOption]]
    )
  }
  def descriptor: com.google.protobuf.Descriptors.Descriptor = DescriptorProtoCompanion.descriptor.getMessageTypes.get(9)
  def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = {
    require(__field.getContainingType() == descriptor, "FieldDescriptor does not match message type.")
    var __out: com.trueaccord.scalapb.GeneratedMessageCompanion[_] = null
    __field.getNumber match {
      case 999 => __out = com.google.protobuf.descriptor.UninterpretedOption
    }
  __out
  }
  def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = {
    require(__field.getContainingType() == descriptor, "FieldDescriptor does not match message type.")
    __field.getNumber match {
      case 9 => com.google.protobuf.descriptor.FileOptions.OptimizeMode
    }
  }
  lazy val defaultInstance = com.google.protobuf.descriptor.FileOptions(
  )
  sealed trait OptimizeMode extends com.trueaccord.scalapb.GeneratedEnum {
    type EnumType = OptimizeMode
    def isSpeed: Boolean = false
    def isCodeSize: Boolean = false
    def isLiteRuntime: Boolean = false
    def isUnrecognized: Boolean = false
    def companion: com.trueaccord.scalapb.GeneratedEnumCompanion[OptimizeMode] = OptimizeMode
  }
  
  object OptimizeMode extends com.trueaccord.scalapb.GeneratedEnumCompanion[OptimizeMode] {
    implicit def enumCompanion: com.trueaccord.scalapb.GeneratedEnumCompanion[OptimizeMode] = this
    @SerialVersionUID(0L)
    case object SPEED extends OptimizeMode {
      val value = 1
      val index = 0
      val name = "SPEED"
      override def isSpeed: Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object CODE_SIZE extends OptimizeMode {
      val value = 2
      val index = 1
      val name = "CODE_SIZE"
      override def isCodeSize: Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object LITE_RUNTIME extends OptimizeMode {
      val value = 3
      val index = 2
      val name = "LITE_RUNTIME"
      override def isLiteRuntime: Boolean = true
    }
    
    @SerialVersionUID(0L)
    case class Unrecognized(value: Int) extends OptimizeMode {
      val name = "UNRECOGNIZED"
      val index = -1
      override def isUnrecognized: Boolean = true
    }
    
    lazy val values = scala.collection.Seq(SPEED, CODE_SIZE, LITE_RUNTIME)
    def fromValue(value: Int): OptimizeMode = value match {
      case 1 => SPEED
      case 2 => CODE_SIZE
      case 3 => LITE_RUNTIME
      case __other => Unrecognized(__other)
    }
    def descriptor: com.google.protobuf.Descriptors.EnumDescriptor = com.google.protobuf.descriptor.FileOptions.descriptor.getEnumTypes.get(0)
  }
  implicit class FileOptionsLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, com.google.protobuf.descriptor.FileOptions]) extends com.trueaccord.lenses.ObjectLens[UpperPB, com.google.protobuf.descriptor.FileOptions](_l) {
    def javaPackage: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.getJavaPackage)((c_, f_) => c_.copy(javaPackage = Some(f_)))
    def optionalJavaPackage: com.trueaccord.lenses.Lens[UpperPB, scala.Option[String]] = field(_.javaPackage)((c_, f_) => c_.copy(javaPackage = f_))
    def javaOuterClassname: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.getJavaOuterClassname)((c_, f_) => c_.copy(javaOuterClassname = Some(f_)))
    def optionalJavaOuterClassname: com.trueaccord.lenses.Lens[UpperPB, scala.Option[String]] = field(_.javaOuterClassname)((c_, f_) => c_.copy(javaOuterClassname = f_))
    def javaMultipleFiles: com.trueaccord.lenses.Lens[UpperPB, Boolean] = field(_.getJavaMultipleFiles)((c_, f_) => c_.copy(javaMultipleFiles = Some(f_)))
    def optionalJavaMultipleFiles: com.trueaccord.lenses.Lens[UpperPB, scala.Option[Boolean]] = field(_.javaMultipleFiles)((c_, f_) => c_.copy(javaMultipleFiles = f_))
    def javaGenerateEqualsAndHash: com.trueaccord.lenses.Lens[UpperPB, Boolean] = field(_.getJavaGenerateEqualsAndHash)((c_, f_) => c_.copy(javaGenerateEqualsAndHash = Some(f_)))
    def optionalJavaGenerateEqualsAndHash: com.trueaccord.lenses.Lens[UpperPB, scala.Option[Boolean]] = field(_.javaGenerateEqualsAndHash)((c_, f_) => c_.copy(javaGenerateEqualsAndHash = f_))
    def javaStringCheckUtf8: com.trueaccord.lenses.Lens[UpperPB, Boolean] = field(_.getJavaStringCheckUtf8)((c_, f_) => c_.copy(javaStringCheckUtf8 = Some(f_)))
    def optionalJavaStringCheckUtf8: com.trueaccord.lenses.Lens[UpperPB, scala.Option[Boolean]] = field(_.javaStringCheckUtf8)((c_, f_) => c_.copy(javaStringCheckUtf8 = f_))
    def optimizeFor: com.trueaccord.lenses.Lens[UpperPB, com.google.protobuf.descriptor.FileOptions.OptimizeMode] = field(_.getOptimizeFor)((c_, f_) => c_.copy(optimizeFor = Some(f_)))
    def optionalOptimizeFor: com.trueaccord.lenses.Lens[UpperPB, scala.Option[com.google.protobuf.descriptor.FileOptions.OptimizeMode]] = field(_.optimizeFor)((c_, f_) => c_.copy(optimizeFor = f_))
    def goPackage: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.getGoPackage)((c_, f_) => c_.copy(goPackage = Some(f_)))
    def optionalGoPackage: com.trueaccord.lenses.Lens[UpperPB, scala.Option[String]] = field(_.goPackage)((c_, f_) => c_.copy(goPackage = f_))
    def ccGenericServices: com.trueaccord.lenses.Lens[UpperPB, Boolean] = field(_.getCcGenericServices)((c_, f_) => c_.copy(ccGenericServices = Some(f_)))
    def optionalCcGenericServices: com.trueaccord.lenses.Lens[UpperPB, scala.Option[Boolean]] = field(_.ccGenericServices)((c_, f_) => c_.copy(ccGenericServices = f_))
    def javaGenericServices: com.trueaccord.lenses.Lens[UpperPB, Boolean] = field(_.getJavaGenericServices)((c_, f_) => c_.copy(javaGenericServices = Some(f_)))
    def optionalJavaGenericServices: com.trueaccord.lenses.Lens[UpperPB, scala.Option[Boolean]] = field(_.javaGenericServices)((c_, f_) => c_.copy(javaGenericServices = f_))
    def pyGenericServices: com.trueaccord.lenses.Lens[UpperPB, Boolean] = field(_.getPyGenericServices)((c_, f_) => c_.copy(pyGenericServices = Some(f_)))
    def optionalPyGenericServices: com.trueaccord.lenses.Lens[UpperPB, scala.Option[Boolean]] = field(_.pyGenericServices)((c_, f_) => c_.copy(pyGenericServices = f_))
    def deprecated: com.trueaccord.lenses.Lens[UpperPB, Boolean] = field(_.getDeprecated)((c_, f_) => c_.copy(deprecated = Some(f_)))
    def optionalDeprecated: com.trueaccord.lenses.Lens[UpperPB, scala.Option[Boolean]] = field(_.deprecated)((c_, f_) => c_.copy(deprecated = f_))
    def ccEnableArenas: com.trueaccord.lenses.Lens[UpperPB, Boolean] = field(_.getCcEnableArenas)((c_, f_) => c_.copy(ccEnableArenas = Some(f_)))
    def optionalCcEnableArenas: com.trueaccord.lenses.Lens[UpperPB, scala.Option[Boolean]] = field(_.ccEnableArenas)((c_, f_) => c_.copy(ccEnableArenas = f_))
    def objcClassPrefix: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.getObjcClassPrefix)((c_, f_) => c_.copy(objcClassPrefix = Some(f_)))
    def optionalObjcClassPrefix: com.trueaccord.lenses.Lens[UpperPB, scala.Option[String]] = field(_.objcClassPrefix)((c_, f_) => c_.copy(objcClassPrefix = f_))
    def csharpNamespace: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.getCsharpNamespace)((c_, f_) => c_.copy(csharpNamespace = Some(f_)))
    def optionalCsharpNamespace: com.trueaccord.lenses.Lens[UpperPB, scala.Option[String]] = field(_.csharpNamespace)((c_, f_) => c_.copy(csharpNamespace = f_))
    def uninterpretedOption: com.trueaccord.lenses.Lens[UpperPB, scala.collection.Seq[com.google.protobuf.descriptor.UninterpretedOption]] = field(_.uninterpretedOption)((c_, f_) => c_.copy(uninterpretedOption = f_))
  }
  final val JAVA_PACKAGE_FIELD_NUMBER = 1
  final val JAVA_OUTER_CLASSNAME_FIELD_NUMBER = 8
  final val JAVA_MULTIPLE_FILES_FIELD_NUMBER = 10
  final val JAVA_GENERATE_EQUALS_AND_HASH_FIELD_NUMBER = 20
  final val JAVA_STRING_CHECK_UTF8_FIELD_NUMBER = 27
  final val OPTIMIZE_FOR_FIELD_NUMBER = 9
  final val GO_PACKAGE_FIELD_NUMBER = 11
  final val CC_GENERIC_SERVICES_FIELD_NUMBER = 16
  final val JAVA_GENERIC_SERVICES_FIELD_NUMBER = 17
  final val PY_GENERIC_SERVICES_FIELD_NUMBER = 18
  final val DEPRECATED_FIELD_NUMBER = 23
  final val CC_ENABLE_ARENAS_FIELD_NUMBER = 31
  final val OBJC_CLASS_PREFIX_FIELD_NUMBER = 36
  final val CSHARP_NAMESPACE_FIELD_NUMBER = 37
  final val UNINTERPRETED_OPTION_FIELD_NUMBER = 999
}
