// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package com.trueaccord.scalapb.scalapb



object ScalapbProto {
  private lazy val ProtoBytes: Array[Byte] =
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChVzY2FsYXBiL3NjYWxhcGIucHJvdG8SB3NjYWxhcGIaIGdvb2dsZS9wcm90b2J1Zi9kZXNjcmlwdG9yLnByb3RvItoBCg5TY
  2FsYVBiT3B0aW9ucxIhCgxwYWNrYWdlX25hbWUYASABKAlSC3BhY2thZ2VOYW1lEiEKDGZsYXRfcGFja2FnZRgCIAEoCFILZmxhd
  FBhY2thZ2USFgoGaW1wb3J0GAMgAygJUgZpbXBvcnQSGgoIcHJlYW1ibGUYBCADKAlSCHByZWFtYmxlEh8KC3NpbmdsZV9maWxlG
  AUgASgIUgpzaW5nbGVGaWxlEi0KEnByaW1pdGl2ZV93cmFwcGVycxgGIAEoCFIRcHJpbWl0aXZlV3JhcHBlcnMiVwoOTWVzc2FnZ
  U9wdGlvbnMSGAoHZXh0ZW5kcxgBIAMoCVIHZXh0ZW5kcxIrChFjb21wYW5pb25fZXh0ZW5kcxgCIAMoCVIQY29tcGFuaW9uRXh0Z
  W5kcyJBCgxGaWVsZE9wdGlvbnMSEgoEdHlwZRgBIAEoCVIEdHlwZRIdCgpzY2FsYV9uYW1lGAIgASgJUglzY2FsYU5hbWU6UAoHb
  3B0aW9ucxIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxj8ByABKAsyFy5zY2FsYXBiLlNjYWxhUGJPcHRpb25zUgdvcHRpb
  25zOlMKB21lc3NhZ2USHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMY/AcgASgLMhcuc2NhbGFwYi5NZXNzYWdlT3B0a
  W9uc1IHbWVzc2FnZTpLCgVmaWVsZBIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMY/AcgASgLMhUuc2NhbGFwYi5GaWVsZ
  E9wdGlvbnNSBWZpZWxkQhgKFmNvbS50cnVlYWNjb3JkLnNjYWxhcGI="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, Seq(
      com.google.protobuf.descriptor.DescriptorProtoCompanion.scalaDescriptor
    ))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    com.google.protobuf.DescriptorProtos.getDescriptor()
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
  val options: _root_.com.trueaccord.scalapb.GeneratedExtension[com.google.protobuf.DescriptorProtos.FileOptions, scala.Option[com.trueaccord.scalapb.scalapb.ScalaPbOptions]] =
    _root_.com.trueaccord.scalapb.GeneratedExtension.forOptionalUnknownField(1020, _.getLengthDelimitedList)({__valueIn => _root_.com.trueaccord.scalapb.GeneratedExtension.readMessageFromByteString(com.trueaccord.scalapb.scalapb.ScalaPbOptions)(__valueIn)})
  val message: _root_.com.trueaccord.scalapb.GeneratedExtension[com.google.protobuf.DescriptorProtos.MessageOptions, scala.Option[com.trueaccord.scalapb.scalapb.MessageOptions]] =
    _root_.com.trueaccord.scalapb.GeneratedExtension.forOptionalUnknownField(1020, _.getLengthDelimitedList)({__valueIn => _root_.com.trueaccord.scalapb.GeneratedExtension.readMessageFromByteString(com.trueaccord.scalapb.scalapb.MessageOptions)(__valueIn)})
  val field: _root_.com.trueaccord.scalapb.GeneratedExtension[com.google.protobuf.DescriptorProtos.FieldOptions, scala.Option[com.trueaccord.scalapb.scalapb.FieldOptions]] =
    _root_.com.trueaccord.scalapb.GeneratedExtension.forOptionalUnknownField(1020, _.getLengthDelimitedList)({__valueIn => _root_.com.trueaccord.scalapb.GeneratedExtension.readMessageFromByteString(com.trueaccord.scalapb.scalapb.FieldOptions)(__valueIn)})
}