// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package scalapb.perf.protos

object ProtosProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions
      : Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      scalapb.perf.protos.SimpleMessage,
      scalapb.perf.protos.MessageContainer,
      scalapb.perf.protos.Enum,
      scalapb.perf.protos.EnumVector,
      scalapb.perf.protos.IntVector,
      scalapb.perf.protos.StringMessage
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
    scalapb.Encoding.fromBase64(
      scala.collection.immutable
        .Seq(
          """Cgxwcm90b3MucHJvdG8SDHNjYWxhcGIucGVyZhoVc2NhbGFwYi9zY2FsYXBiLnByb3RvIogBCg1TaW1wbGVNZXNzYWdlEhQKA
  WkYASABKAVCBuI/AxIBaVIBaRIUCgFqGAIgASgFQgbiPwMSAWpSAWoSFAoBaxgDIAEoDEIG4j8DEgFrUgFrEjUKBWNvbG9yGAQgA
  SgOMhMuc2NhbGFwYi5wZXJmLkNvbG9yQgriPwcSBWNvbG9yUgVjb2xvciKEAQoQTWVzc2FnZUNvbnRhaW5lchI3CgNvcHQYASABK
  AsyGy5zY2FsYXBiLnBlcmYuU2ltcGxlTWVzc2FnZUII4j8FEgNvcHRSA29wdBI3CgNyZXAYAiADKAsyGy5zY2FsYXBiLnBlcmYuU
  2ltcGxlTWVzc2FnZUII4j8FEgNyZXBSA3JlcCI9CgRFbnVtEjUKBWNvbG9yGAEgASgOMhMuc2NhbGFwYi5wZXJmLkNvbG9yQgriP
  wcSBWNvbG9yUgVjb2xvciJGCgpFbnVtVmVjdG9yEjgKBmNvbG9ycxgBIAMoDjITLnNjYWxhcGIucGVyZi5Db2xvckIL4j8IEgZjb
  2xvcnNSBmNvbG9ycyIqCglJbnRWZWN0b3ISHQoEaW50cxgBIAMoBUIJ4j8GEgRpbnRzUgRpbnRzIk0KDVN0cmluZ01lc3NhZ2USH
  QoEc3RyMRgBIAEoCUIJ4j8GEgRzdHIxUgRzdHIxEh0KBHN0cjIYAiABKAlCCeI/BhIEc3RyMlIEc3RyMiphCgVDb2xvchIZCgdVT
  ktOT1dOEAAaDOI/CRIHVU5LTk9XThIRCgNSRUQQARoI4j8FEgNSRUQSFQoFR1JFRU4QAhoK4j8HEgVHUkVFThITCgRCTFVFEAMaC
  eI/BhIEQkxVRUIH4j8ESAFoAUrACAoGEgQAAC0BCggKAQwSAwAAEgoJCgIDABIDAgAfCggKAQISAwQAFQoJCgEIEgQGAAkCCgsKA
  wj8BxIEBgAJAgoKCgIFABIECwAQAQoKCgMFAAESAwsFCgoLCgQFAAIAEgMMAg4KDAoFBQACAAESAwwCCQoMCgUFAAIAAhIDDAwNC
  gsKBAUAAgESAw0CCgoMCgUFAAIBARIDDQIFCgwKBQUAAgECEgMNCAkKCwoEBQACAhIDDgIMCgwKBQUAAgIBEgMOAgcKDAoFBQACA
  gISAw4KCwoLCgQFAAIDEgMPAgsKDAoFBQACAwESAw8CBgoMCgUFAAIDAhIDDwkKCgoKAgQAEgQSABcBCgoKAwQAARIDEggVCgsKB
  AQAAgASAxMCDgoMCgUEAAIABRIDEwIHCgwKBQQAAgABEgMTCAkKDAoFBAACAAMSAxMMDQoLCgQEAAIBEgMUAg4KDAoFBAACAQUSA
  xQCBwoMCgUEAAIBARIDFAgJCgwKBQQAAgEDEgMUDA0KCwoEBAACAhIDFQIOCgwKBQQAAgIFEgMVAgcKDAoFBAACAgESAxUICQoMC
  gUEAAICAxIDFQwNCgsKBAQAAgMSAxYCEgoMCgUEAAIDBhIDFgIHCgwKBQQAAgMBEgMWCA0KDAoFBAACAwMSAxYQEQoKCgIEARIEG
  QAcAQoKCgMEAQESAxkIGAoLCgQEAQIAEgMaAhgKDAoFBAECAAYSAxoCDwoMCgUEAQIAARIDGhATCgwKBQQBAgADEgMaFhcKOQoEB
  AECARIDGwIhIiwgIFsoc2NhbGFwYi5maWVsZCkuY29sbGVjdGlvbl90eXBlPSJMaXN0Il07CgoMCgUEAQIBBBIDGwIKCgwKBQQBA
  gEGEgMbCxgKDAoFBAECAQESAxsZHAoMCgUEAQIBAxIDGx8gCgoKAgQCEgQeACABCgoKAwQCARIDHggMCgsKBAQCAgASAx8CEgoMC
  gUEAgIABhIDHwIHCgwKBQQCAgABEgMfCA0KDAoFBAICAAMSAx8QEQoKCgIEAxIEIgAkAQoKCgMEAwESAyIIEgoLCgQEAwIAEgMjA
  hwKDAoFBAMCAAQSAyMCCgoMCgUEAwIABhIDIwsQCgwKBQQDAgABEgMjERcKDAoFBAMCAAMSAyMaGwoKCgIEBBIEJgAoAQoKCgMEB
  AESAyYIEQoLCgQEBAIAEgMnAhoKDAoFBAQCAAQSAycCCgoMCgUEBAIABRIDJwsQCgwKBQQEAgABEgMnERUKDAoFBAQCAAMSAycYG
  QoKCgIEBRIEKgAtAQoKCgMEBQESAyoIFQoLCgQEBQIAEgMrAhIKDAoFBAUCAAUSAysCCAoMCgUEBQIAARIDKwkNCgwKBQQFAgADE
  gMrEBEKCwoEBAUCARIDLAISCgwKBQQFAgEFEgMsAggKDAoFBAUCAQESAywJDQoMCgUEBQIBAxIDLBARYgZwcm90bzM="""
        )
        .mkString
    )
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor
      .buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(
      javaProto,
      _root_.scala.Array(
        scalapb.options.ScalapbProto.javaDescriptor
      )
    )
  }
  @deprecated(
    "Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.",
    "ScalaPB 0.5.47"
  )
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}
